name: Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: npm install
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "package"
      - name: Gather build artifacts
        run: |
          mkdir -p build
          mv *.vsix ./build/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.6
        with:
          name: Contents
          path: build/
          retention-days: 60
          if-no-files-found: error
