name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: npm install
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "publish --pat $VSCE_PAT"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
